/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: nnforge.swigcxx

package nnforge

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrNeural_network_toolset uintptr

func (p SwigcptrNeural_network_toolset) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNeural_network_toolset) SwigIsNeural_network_toolset() {
}

var _wrap_new_neural_network_toolset unsafe.Pointer

func _swig_wrap_new_neural_network_toolset(base uintptr) (_ SwigcptrNeural_network_toolset) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_neural_network_toolset, _swig_p)
	return
}

func NewNeural_network_toolset(arg1 Factory_generator_smart_ptr) (_swig_ret Neural_network_toolset) {
	return _swig_wrap_new_neural_network_toolset(arg1.Swigcptr())
}

var _wrap_delete_neural_network_toolset unsafe.Pointer

func _swig_wrap_delete_neural_network_toolset(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_neural_network_toolset, _swig_p)
	return
}

func DeleteNeural_network_toolset(arg1 Neural_network_toolset) {
	_swig_wrap_delete_neural_network_toolset(arg1.Swigcptr())
}

var _wrap_neural_network_toolset_parse unsafe.Pointer

func _swig_wrap_neural_network_toolset_parse(base SwigcptrNeural_network_toolset, _ int, _ *string) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_neural_network_toolset_parse, _swig_p)
	return
}

func (arg1 SwigcptrNeural_network_toolset) Parse(arg2 int, arg3 *string) (_swig_ret bool) {
	return _swig_wrap_neural_network_toolset_parse(arg1, arg2, arg3)
}

var _wrap_neural_network_toolset_get_action unsafe.Pointer

func _swig_wrap_neural_network_toolset_get_action(base SwigcptrNeural_network_toolset) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_neural_network_toolset_get_action, _swig_p)
	return
}

func (arg1 SwigcptrNeural_network_toolset) Get_action() (_swig_ret string) {
	return _swig_wrap_neural_network_toolset_get_action(arg1)
}

var _wrap_neural_network_toolset_do_action unsafe.Pointer

func _swig_wrap_neural_network_toolset_do_action(base SwigcptrNeural_network_toolset) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_neural_network_toolset_do_action, _swig_p)
	return
}

func (arg1 SwigcptrNeural_network_toolset) Do_action() {
	_swig_wrap_neural_network_toolset_do_action(arg1)
}

type Neural_network_toolset interface {
	Swigcptr() uintptr
	SwigIsNeural_network_toolset()
	Parse(arg2 int, arg3 *string) (_swig_ret bool)
	Get_action() (_swig_ret string)
	Do_action()
}

type SwigcptrPlain uintptr

func (p SwigcptrPlain) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPlain) SwigIsPlain() {
}

var _wrap_plain_init unsafe.Pointer

func _swig_wrap_plain_init() {
	var _swig_p uintptr
	_cgo_runtime_cgocall(_wrap_plain_init, _swig_p)
	return
}

func PlainInit() {
	_swig_wrap_plain_init()
}

type Plain interface {
	Swigcptr() uintptr
	SwigIsPlain()
}

type SwigcptrNnforge uintptr

func (p SwigcptrNnforge) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNnforge) SwigIsNnforge() {
}

var _wrap_nnforge_init unsafe.Pointer

func _swig_wrap_nnforge_init() {
	var _swig_p uintptr
	_cgo_runtime_cgocall(_wrap_nnforge_init, _swig_p)
	return
}

func NnforgeInit() {
	_swig_wrap_nnforge_init()
}

type Nnforge interface {
	Swigcptr() uintptr
	SwigIsNnforge()
}


type SwigcptrFactory_generator_smart_ptr uintptr
type Factory_generator_smart_ptr interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFactory_generator_smart_ptr) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

